"""What the paste-ready code blocks are allowed to say.

A snippet labelled paste-ready is the part of a report most likely to be used
verbatim, so anything wrong inside one is published rather than merely read.
Every case here was generated by a real run against a real site.
"""

from __future__ import annotations

import importlib.util
import json
import os
import sys

import pytest

from conftest import ROOT, SCRIPTS

sys.path.insert(0, SCRIPTS)


def _module(skill):
    path = os.path.join(ROOT, "skills", skill, "scripts", "check.py")
    spec = importlib.util.spec_from_file_location("check_" + skill.replace("-", "_"), path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


SD = _module("structured-data-audit")


# --------------------------------------------------------------------------
# An address comes from markup or it does not go in
# --------------------------------------------------------------------------

SCRAPED_ONLY = [{
    "url": "https://example.test/",
    "contact_facts": {"street_hint": "9 Let's Circle", "postcode_hint": "15880",
                      "has_address": True, "declared_phones": []},
    "jsonld": [],
}]

DECLARED = [{
    "url": "https://example.test/",
    "contact_facts": {"street_hint": "2026 Shake Shack Hits the Road",
                      "postcode_hint": "11368", "has_address": True,
                      "declared_phones": []},
    "jsonld": [{"@type": "Organization", "address": {
        "@type": "PostalAddress", "streetAddress": "41 Walmgate",
        "addressLocality": "York", "postalCode": "YO1 9TT"}}],
}]


def test_a_regex_match_never_becomes_a_published_address():
    """"9 Let's Circle" is a $9 nail polish; "15880" is a colour-index code."""
    facts = SD._contact_facts_for_snippet(SCRAPED_ONLY)
    assert "address" not in facts
    assert "postal_code" not in facts
    assert facts["has_address"] is True, (
        "the site does mention something address-shaped; that is a signal, not a fact")


def test_a_declared_address_is_used_in_full():
    facts = SD._contact_facts_for_snippet(DECLARED)
    assert facts["address"] == "41 Walmgate"
    assert facts["postal_code"] == "YO1 9TT"
    assert facts["locality"] == "York"


def test_the_declared_address_wins_over_the_scraped_one():
    """The scraped value here is a year plus a blog headline."""
    assert SD._contact_facts_for_snippet(DECLARED)["address"] != \
        "2026 Shake Shack Hits the Road"


# --------------------------------------------------------------------------
# sameAs asserts identity, so it must be the brand's own accounts
# --------------------------------------------------------------------------

MIXED = [{"social_profiles": {
    "X": "https://x.com/james406",
    "GitHub": "https://github.com/PostHog",
    "Wikipedia": "https://en.wikipedia.org/wiki/ACID",
    "YouTube": "https://www.youtube.com/@posthog",
    "LinkedIn": "https://www.linkedin.com/company/posthog",
}}]


def test_a_founders_personal_account_is_not_the_brands_profile():
    same_as = SD._all_same_as(MIXED, {"name": "PostHog"})
    assert "https://x.com/james406" not in same_as


def test_an_unrelated_encyclopedia_article_is_not_the_brands_profile():
    same_as = SD._all_same_as(MIXED, {"name": "PostHog"})
    assert "https://en.wikipedia.org/wiki/ACID" not in same_as


def test_the_brands_own_accounts_survive():
    same_as = SD._all_same_as(MIXED, {"name": "PostHog"})
    assert set(same_as) == {
        "https://github.com/PostHog",
        "https://www.youtube.com/@posthog",
        "https://www.linkedin.com/company/posthog",
    }


@pytest.mark.parametrize("handle,brand", [
    ("getpostman", "Postman"), ("acmehq", "Acme"), ("theacme", "Acme"),
    ("acme", "Acme Ltd"),
])
def test_ordinary_handle_variations_still_match(handle, brand):
    same_as = SD._all_same_as(
        [{"social_profiles": {"X": "https://x.com/" + handle}}], {"name": brand})
    assert same_as, "{} should be accepted as {}'s handle".format(handle, brand)


def test_no_brand_name_means_no_filtering():
    """Better to publish the shape-checked list than to silently drop it all."""
    assert SD._all_same_as(MIXED, {"name": ""}) == sorted(
        MIXED[0]["social_profiles"].values())


# --------------------------------------------------------------------------
# A chain is an Organization that has local businesses
# --------------------------------------------------------------------------

def _snapshot(pages):
    return {"pages": pages, "origin": "https://example.test", "site": "example.test"}


def _branch(city, postcode):
    return {"url": "https://example.test/l/" + city, "page_type": "location", "jsonld": [
        {"@type": "Restaurant", "name": "Example " + city,
         "address": {"@type": "PostalAddress", "addressLocality": city,
                     "postalCode": postcode}}]}


def test_many_branches_make_an_organization_not_a_local_business():
    """A 500-branch chain was handed markup calling it one storefront."""
    snapshot = _snapshot([_branch("York", "YO1 9TT"), _branch("Leeds", "LS1 1AA")])
    assert SD._identity_type(snapshot, snapshot["pages"], {}) == "Organization"


def test_one_visitable_place_is_still_a_local_business():
    snapshot = _snapshot([_branch("York", "YO1 9TT")])
    assert SD._identity_type(snapshot, snapshot["pages"], {}) == "LocalBusiness"


def test_an_address_in_a_footer_does_not_make_a_charity_a_local_business():
    """Nearly every organisation publishes an address, for legal reasons."""
    snapshot = _snapshot([{"url": "https://example.test/", "page_type": "home", "jsonld": []}])
    assert SD._identity_type(snapshot, snapshot["pages"],
                             {"has_address": True}) == "Organization"


# --------------------------------------------------------------------------
# Variant-level offers are richer markup, not missing markup
# --------------------------------------------------------------------------

def test_a_product_group_variant_offer_is_found():
    """Reading only the top level called complete markup "no offers object"."""
    node = {"@type": "ProductGroup", "hasVariant": [
        {"@type": "Product", "offers": {"@type": "Offer", "price": 95,
                                        "priceCurrency": "USD",
                                        "availability": "InStock"}}]}
    offer = SD._offer_of(node)
    assert offer and offer["price"] == 95


def test_a_flat_product_offer_is_still_found():
    assert SD._offer_of({"@type": "Product", "offers": {"price": 10}})["price"] == 10


def test_a_product_with_no_offer_anywhere_is_still_reported():
    assert SD._offer_of({"@type": "Product"}) is None


# --------------------------------------------------------------------------
# Advice written for a seller, given to people who sell nothing
# --------------------------------------------------------------------------

FACT = _module("fact-extractability-audit")

sys.path.insert(0, SCRIPTS)
from audit_common import sells_something  # noqa: E402


def _page(url, body="", page_type="home", jsonld_types=()):
    return {"url": url, "body_text": body, "page_type": page_type,
            "jsonld_types": list(jsonld_types), "jsonld": []}


def test_a_charity_is_not_a_seller():
    """It was told it "never states its pricing", with a fix reading
    "contact sales for a quote"."""
    pages = [_page("https://example.test/", "We provide medical care in crisis zones."),
             _page("https://example.test/who-we-are", "Founded in 1971.", "about")]
    assert sells_something({"pages": pages}, pages) is False


def test_a_free_software_project_is_not_a_seller():
    pages = [_page("https://example.test/", "Free and open source software.")]
    assert sells_something({"pages": pages}, pages) is False


def test_a_shop_is_a_seller():
    pages = [_page("https://example.test/p/mug", "Walmgate mug. 18.00 GBP. Add to cart.",
                   "product")]
    assert sells_something({"pages": pages}, pages) is True


def test_a_pricing_page_makes_a_seller():
    pages = [_page("https://example.test/pricing", "Plans and packages.", "pricing")]
    assert sells_something({"pages": pages}, pages) is True


def test_commerce_markup_makes_a_seller():
    pages = [_page("https://example.test/x", "", "other", ["Offer"])]
    assert sells_something({"pages": pages}, pages) is True


def test_the_worked_example_does_not_invent_a_pricing_plan():
    """The snippet offered "$X per month on the Starter plan and $Y on Growth"
    to a charity's FAQ, a database engine, a video toolkit and a museum."""
    example = FACT._answer_first_example(False, "Example Relief")
    assert "Starter plan" not in example
    assert "per month" not in example
    assert "What is Example Relief?" in example


def test_the_worked_example_is_about_price_when_there_is_one():
    example = FACT._answer_first_example(True, "Acme")
    assert "How much does it cost?" in example
    assert "Starter plan" not in example, "still no invented plan names"


def test_free_software_is_described_as_free_not_as_quote_on_request():
    """A project's report said it "states pricing is on request", a sentence
    that appears nowhere on it."""
    assert FACT.COSTS_NOTHING_RE.search("FFmpeg is free and open-source software")
    assert not FACT.QUOTE_ON_REQUEST_RE.search("FFmpeg is free and open-source software")
    assert FACT.QUOTE_ON_REQUEST_RE.search("Contact us for a quote")
